### ISSUE TITLE
nlinv not respective "-m"

### ISSUE THREAD

**Issue by sidward** [mrirecon/enlive#3]
Hello!

I am running BART version: v0.7.00-164-g4ff6333. I am trying to get 2 sets of sensitivity maps on some 2D non-cartesian data as in your heart example. I am calling nlinv as follows:

`bart nlinv -t buffer/trj -d 5 -U -m 3 buffer/ksp buffer/rec buffer/mps`

However, the resulting reconstruction and sensitivity maps do not seem to have the relaxed multiple sensitivity maps. Please let me know if I am doing anything wrong.

The debug output (not including iteration prints) is as follows:
```
Est. image size: 1 128 128
Start gridding psf ...nufft kernel dims: [  1 1688 500   1   1   1   1   1   1   1   1   1   1   1   1   1   1 ]
nufft psf dims:    [  1 256 256   1   1   1   1   1   1   1   1   1   1   1   1   1   1 ]
nufft traj dims:   [  3 1688 500   1   1   1   1   1   1   1   1   1   1   1   1   1   1 ]
Allocating 844000 (vs. 909536) + 65536
ksp : [  1 1688 500   1   1   1   1   1   1   1   1   1   1   1   1   1   1 ]
cim : [  1 256 256   1   1   1   1   1   1   1   1   1   1   1   1   1   1 ]
traj: [  3 1688 500   1   1   1   1   1   1   1   1   1   1   1   1   1   1 ]
finished
Start creating nufft-objects...ksp : [  1 1688 500  12   1   1   1   1   1   1   1   1   1   1   1   1 ]
cim : [  1 256 256  12   1   1   1   1   1   1   1   1   1   1   1   1 ]
traj: [  3 1688 500   1   1   1   1   1   1   1   1   1   1   1   1   1 ]
finished
Scaling: 0.000001
```

I am assuming 12 coils. I am expecting sensitivity maps of dimensions (1, 128, 128, 12, 2) and a reconstructed image of dimensions (1, 128, 128, 1, 2).

Thanks for the help!

**Comment by hcmh** [comment]
Hey, 

this is a bug in bart, where it will just overwrite the number of maps in non-Cartesian ENLIVE. I just fixed it on the bart master branch.

This repo is actually not affected, as it does nufft gridding "by hand" before calling nlinv.

**Comment by sidward** [comment]
Thanks  much!
